### ISSUE TITLE
Looks fake

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/sindresorhus-cli#2]
This looks fake. If the real @sindresorhus did that there would be 2 packages - one with just the JS API and another wrapping it in CLI.

:laughing: I hope you get the joke! Kudos to the originality!

**Comment by sindresorhus** [comment]
😝

![giphy](https://user-images.githubusercontent.com/170270/39858306-5b810aca-5460-11e8-8c7e-c156b2ec5322.gif)
